---
title: "p8105_hw4_cz2492_problem2"
author: "Cenai Zhang"
date: "10/25/2017"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(haven)
library(ggridges)
library(janitor)
```

# Read and clean dataset
```{r}
pols_month = read_csv("pols-month.csv") %>% 
  mutate(mon = as.POSIXct(mon)) %>% 
  mutate(mon = lubridate::floor_date(mon, "month")) %>% 
  rename(date = mon)

gdp = read_csv("GDP.csv") %>% 
  clean_names() %>% 
  mutate(date = as.POSIXct(date)) %>%
  mutate(date = lubridate::floor_date(date, "month"))

gdp_month = left_join(pols_month, gdp, by = "date")
```

# Make the plot showing the change of GDP over time.
```{r}
gdp_month %>%
  mutate(., prez_gop = replace(prez_gop, prez_gop == 1 | prez_gop ==2, "Republican"),
            prez_gop = replace(prez_gop, prez_gop == 0, "Democrat")) %>%
  select(., date, president = prez_gop, value) %>%
  filter(., !is.na(value) & !value == ".") %>%
  mutate(., value = as.numeric(value)) %>%
  ggplot(., aes(x = date, y = value, color = president)) +
  geom_point(alpha = 0.5) +
  geom_smooth(se=F) +
  labs(title = "Plot of GDP Values over Time",
       x = "Time",
       y = "GDP") +
  theme_bw()
```